openapi: 3.0.3
info:
  description: This API receives bus data from a transit system in a large metropolitian city.
  version: "1.0.0"
  title: Bus API
  contact:
    email: sduong9@my.bcit.ca
paths:
  /bus/ridership:
    get:
      summary: Get a ridership event at the requested index
      operationId: app.get_ridership_reading
      parameters:
        - name: index
          in: query
          description: Index of ridership event
          schema:
            type: integer 
            example: 3
      responses:
        '200':
          description: Successfully returned ridership data at requested index
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/RidershipReading"
        '404':
          description: No found

    
  /bus/fuel:
    get:
      summary: Get a fuel dership event at the requested index
      operationId: app.get_fuel_reading
      parameters:
        - name: index
          in: query
          description: Index of fuel event
          schema:
            type: integer 
            example: 3
      responses:
        '200':
          description: Successfully returned fuel data at requested index
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/FuelReading"
        '404':
          description: Not found

  /stats:
    get:
      summary: Returns number of events in queue
      operationId: app.get_stats
      responses:
        '200':
          description: Successfully returned event queue stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueStats'

components:
  schemas:
    RidershipReading:
      required:
        - trace_id
        - bus_id
        - route_name
        - stop_id
        - passengers_boarded
        - recorded_timestamp
        - batch_timestamp
      properties:
        trace_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        bus_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        stop_id:
          type: number
          example: 25519
        route_name:
          type: string
          example: "25 UBC"
        passengers_boarded:
          type: number
          example: 7
        recorded_timestamp:
          type: string
          format: date-time
          example: "2016-08-29 09:12:33"
        batch_timestamp:
          type: string
          format: date-time
          example: "2016-08-29 09:12:33"
      type: object

    FuelReading:
      required:
        - trace_id
        - bus_id
        - route_name
        - fuel_litres
        - recorded_timestamp
        - batch_timestamp
      properties:
        bus_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        bus_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        route_name:
          type: string
          example: "25 UBC"
        fuel_litres:
          type: number
          example: 2.3
        recorded_timestamp:
          type: string
          format: date-time
          example: "2016-08-29 09:12:33"
        batch_timestamp:
          type: string
          format: date-time
          example: "2016-08-29 09:12:33"
      type: object

    QueueStats:
      required:
        - num_ridership_readings
        - num_fuel_readings
      properties:
        num_ridership_readings:
          type: integer
          example: 3
        num_fuel_readings:
          type: integer
          example: 3