apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: mysql-env
          image: mysql_custom:latest
          name: service-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: service-db
      restartPolicy: Always
      volumes:
        - name: service-db
          persistentVolumeClaim:
            claimName: service-db
