apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: service-db
  name: service-db
  namespace: bakery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi