apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: processing
  name: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processing
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: processing
    spec:
      containers:
        - image: processing-svc:latest
          name: processing-svc
          ports:
            - containerPort: 8100
              protocol: TCP
      restartPolicy: Always
