apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage
  name: storage-deploy
  namespace: bakery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - image: fountum/storage-svc:latest
          name: storage
          ports:
            - containerPort: 8090
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storage
  name: storage-svc
  namespace: bakery
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    app: storage
