services:
  web-svr:
    image: "caddy:latest"
    container_name: web-server
    restart: always
    build:
      context: ../caddy
    depends_on:
      - auth 
    ports:
      - "80:80"

  mysql:
    image: "mysql_custom:latest"
    container_name: service-db
    restart: always
    build:
      context: ../mysql
    ports: 
      - "3306:3306"
    env_file: "mysql.env"
    volumes:
      - service-db:/var/lib/mysql
  
  auth:
    image: "webapp:latest"
    container_name: web-app
    build:
      context: ../auth
    depends_on:
      - mysql
      - receiver
    env_file: "app.env"
    ports:
      - "3001:3001"


  receiver:
    image: "receiver-svc:latest"
    container_name: receiver-svc
    build:
      context: ../receiver
    depends_on:
      - storage
    ports:
      - "8080:8080"
  
  storage:
    image: "storage-svc:latest"
    container_name: storage-svc
    build:
      context: ../storage
    depends_on:
      - mysql
    ports: 
      - "8090:8090"

  processing:
    image: "processing-svc:latest"
    container_name: processing-svc
    build:
      context: ../processing
    depends_on:
      - storage
    ports:
      - "8100:8100"
volumes:
  service-db:
