openapi: 3.0.3
info:
  description: This API receives financial data from inputted by users on a webapp.
  version: "1.0.0"
  title: Sales Api
  contact:
    email: sduong9@my.bcit.ca
paths:
  /sales:
    post:
      summary: Reports sales data.
      operationId: app.report_sales
      description: Adds sales data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalesReport'
      responses:
        '201':
          description: batch successfully received
        '400':
          description: 'invalid input, object invalid'

components:
  schemas:
    SalesReport:
      required:
        - customers
        - cookies_sold
        - income
      properties:
        customers:
          type: integer
          example: 7777
        cookies_sold:
          type: integer
          example: 8888
        income:
          type: number
          example: 9999.00
      type: object