openapi: 3.0.3
info:
  description: This API receives bus data from a transit system in a large metropolitian city.
  version: "1.0.0"
  title: Sales API
  contact:
    email: sduong9@my.bcit.ca
paths:
  /sales:
    post:
      summary: Reports sales data.
      operationId: app.report_sales
      description: Adds sales data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalesReport'
      responses:
        '201':
          description: batch successfully received
        '400':
          description: 'invalid input, object invalid'
    get:
      summary: Gets a batch of sales data in a certain period of time
      operationId: app.get_sales
      parameters:
        - name: start_timestamp
          in: query
          description: Start of date range
          schema:
            type: string
            format: date-time 
            example: 2016-08-29 09:12:33
        - name: end_timestamp
          in: query
          description: End of date range
          schema:
            type: string
            format: date-time
            example: 2016-08-29 09:12:33
      responses:
        '200':
          description: Successfully returned an array of sale data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SalesReport"


components:
  schemas:
    SalesReport:
      required:
        - trace_id
        - customers
        - cookies_sold
        - income
        - reported_time
      properties:
        trace_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        customers:
          type: integer
          example: 7777
        cookies_sold:
          type: integer
          example: 8888
        income:
          type: number
          example: 9999.00
        reported_time:
          type: string
          format: date-time
          example: "2016-08-29 09:12:33"
      type: object